project:
  type: book

book:
  title: "Bayesian Analysis with Python"
  subtitle: "An introduction to probabilistic modeling"
  author: "Osvaldo Martin"
  chapters:
    - index.qmd
    - chp_01.qmd
    - chp_02.qmd
    - chp_03.qmd
    # - chp_04.qmd
    # - chp_05.qmd
    # - chp_06.qmd
    # - chp_07.qmd
    # - chp_08.qmd
    # - chp_09.qmd
    # - chp_10.qmd
    # - chp_11.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme: lumen
  pdf:
    toc: true
    documentclass: scrreprt
    include-in-header: preamble.tex
    code-block-bg: "#f5f5f5"
    monofont: Roboto
  epub:
    cover-image: cover.png
    toc: true
  docx:
    toc: true
    number-sections: false
    code-block-background: true
    code-block-bg: "#f5f5f5"
    monofont: Roboto
    highlight-style: monochrome
    standalone: true
    dpi: 300
