project:
  type: book

book:
  title: "Bayesian Analysis with Python"
  subtitle: "An introduction to probabilistic modeling"
  author: "Osvaldo Martin"
  chapters:
    - index.qmd
    #- chp_01.qmd
    - chp_02.qmd
    #- chp_03.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme: lumen
  pdf:
    toc: true
    documentclass: scrreprt
    include-in-header: preamble.tex
    code-block-bg: "#f5f5f5"
    monofont: Roboto
  epub:
    cover-image: cover.png
    toc: true
  docx:
    toc: true
    code-block-bg: "#f5f5f5"
    monofont: Roboto
    highlight-style: monochrome
